<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Cirreum.Runtime</RootNamespace>
		<Description>The Cirreum SecertsProvider for the Cirreum Runtime Server.</Description>
		<PackageTags>cirreum;runtime;server;secrets;provider</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Cirreum.Logging.Deferred" Version="1.0.103" />
		<PackageReference Include="Cirreum.SecretsProvider" Version="1.0.3" />
	</ItemGroup>

</Project>
